Upgrade to Hydra SDK v0.2.1 (#1)

diff --git a/scripts/hydra b/scripts/hydra
--- a/scripts/hydra
+++ b/scripts/hydra
@@ -1,5 +1,27 @@
 #!/usr/bin/env bash
 
+set_docker_compose() {
+  if [ -x "$(command -v docker)" ] && [ "$(docker --version | awk '{print $3}' | cut -d'-' -f1 | cut -d'.' -f1)" -ge "20" ]; then
+    # Version 2 syntax
+    dockercompose="docker compose"
+  elif [ -x "$(command -v docker-compose)" ]; then
+    # Version 1 syntax
+    dockercompose="docker-compose"
+    echo ""
+    echo "You only have the older docker compose installed. It should work fine for now."
+    echo "The older syntax will be used... $dockercompose"
+    echo ""
+    echo "It is recommended that you install the latest version of docker compose for better compatibility in future hydra builds:"
+    echo "  https://docs.docker.com/compose/install/linux/"
+    echo ""
+  else
+    echo "Docker Compose not found"
+    echo "To proceed, you need to make sure it is installed:"
+    echo "  https://docs.docker.com/compose/install/linux/"
+    exit 1
+  fi
+}
+
 check_if_docker_is_running() {
   if ! docker info &>/dev/null; then
     echo "You need to execute Docker service first to run the script."
@@ -10,14 +32,14 @@ check_if_docker_is_running() {
 check_if_github_token_is_valid() {
   if curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user | grep -q "Bad credentials"; then
     echo "Invalid GITHUB_TOKEN"
-    exit
+    exit 1
   fi
 }
 
 run_container() {
-  cd $1 || exit
+  cd $1
   echo "Starting $1 image ..."
-  docker-compose up -d
+  $dockercompose up -d
   echo "$1 image started"
 
   if [[ ! -z "$2" ]]; then
@@ -25,7 +47,7 @@ run_container() {
       if ! curl $2 &>/dev/null; then
         if [ $i -eq 10 ]; then
           echo "Could not find the $1 instance, make sure to run the $1 container"
-          exit
+          exit 1
         fi
         echo "$1 still booting... waiting 30s ($i/10)"
         sleep 30
@@ -44,7 +66,7 @@ checkout_tessellation_version() {
     cd ../
   else
     echo "Invalid version"
-    exit
+    exit 1
   fi
 }
 
@@ -86,16 +108,16 @@ create_docker_custom_network() {
 
 destroy_container() {
   echo "Destroying $1 container"
-  cd infra/docker/$1 || exit
-  docker-compose down --remove-orphans
+  cd infra/docker/$1
+  $dockercompose down --remove-orphans
   cd ../../../
   echo "$1 container destroyed"
 }
 
 stop_container() {
   echo "Stopping $1 container"
-  cd infra/docker/$1 || exit
-  docker-compose stop
+  cd infra/docker/$1
+  $dockercompose stop
   cd ../../../
   echo "$1 container stopped"
 }
@@ -165,7 +187,7 @@ join_l1_global_nodes() {
 check_if_project_name_is_set() {
   if [[ -z "$PROJECT_NAME" ]]; then
     echo "You should provide the PROJECT_NAME on .env file"
-    exit
+    exit 1
   fi
 }
 
@@ -173,7 +195,7 @@ check_if_project_directory_exists() {
   cd source/
   if [ ! -d "project/$PROJECT_NAME" ]; then
     echo "You must install a framework before building. Run hydra install first"
-    exit
+    exit 1
   fi
   cd ..
 }
@@ -195,9 +217,11 @@ install() {
   echo "Installing hydra ..."
   echo "Installing Framework..."
   create_template project $PROJECT_NAME
-
-  chmod -R +w .git
-  rm -r .git
+  chmod a+rwx infra/docker/monitoring/grafana/storage
+  if [ -d ".git" ]; then
+    chmod -R +w .git
+    rm -r .git
+  fi
   echo "Installed"
 }
 
@@ -209,6 +233,7 @@ install() {
 # @option --only                          Build specific layer. Options: global-l0, dag-l1, currency-l0, currency-l1, monitoring
 # @option --tessellation_version          Tessellation repo branch to build the JARS. Default main
 build() {
+  set_docker_compose
   OUTPUT_YELLOW=$(tput setaf 3)
   OUTPUT_WHITE=$(tput setaf 7)
   check_if_docker_is_running
@@ -229,7 +254,7 @@ build() {
 
   if [[ -z "$GITHUB_TOKEN" && "$argc_only" != "monitoring" ]]; then
     echo "You should provide the GITHUB_TOKEN on .env file"
-    exit
+    exit 1
   fi
 
   if [[ -z "$argc_only" || "$argc_only" != "monitoring" ]]; then
@@ -237,18 +262,18 @@ build() {
     echo "P12 files should be inserted on source/p12-files directory"
     if [ ! -f "../source/p12-files/$P12_GENESIS_FILE_NAME" ]; then
       echo "File does not exists"
-      exit
+      exit 1
     fi
 
     if [[ -z "$argc_only" || "$argc_only" == "dag-l1" || "$argc_only" == "currency-l1" || ! -z "$argc_include_dag_l1" ]]; then
       if [ ! -f "../source/p12-files/$P12_NODE_2_FILE_NAME" ]; then
         echo "File does not exists"
-        exit
+        exit 1
       fi
 
       if [ ! -f "../source/p12-files/$P12_NODE_3_FILE_NAME" ]; then
         echo "File does not exists"
-        exit
+        exit 1
       fi
     fi
   fi
@@ -266,7 +291,7 @@ build() {
   if [ ! -z "$argc_only" ]; then
     if [[ ! $VALID_ONLY_OPTIONS =~ (^|[[:space:]])$argc_only($|[[:space:]]) ]]; then
       echo "You should provide a valid only option"
-      exit
+      exit 1
     fi
   fi
 
@@ -285,8 +310,8 @@ build() {
 
   if [[ -z "$(docker images -q ubuntu-with-java-and-sbt)" || ! -z "$argc_rebuild_tessellation" ]]; then
     echo "Building ubuntu shared image..."
-    cd ubuntu-with-java-and-sbt || exit
-    docker-compose build --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION
+    cd ubuntu-with-java-and-sbt
+    $dockercompose build --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION
     cd ../
     echo "Ubuntu image built"
   fi
@@ -294,13 +319,13 @@ build() {
   if [[ -z "$argc_only" || "$argc_only" == "global-l0" ]]; then
     export SHOULD_RESET_GENESIS_FILE=true
 
-    cd global-l0 || exit
+    cd global-l0
     if [ ! -z "$argc_no_cache" ]; then
       echo "Building Global L0 image... (NO CACHE)"
-      docker-compose build --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_KEY_ALIAS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD=$P12_GENESIS_FILE_PASSWORD --no-cache
+      $dockercompose build --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_KEY_ALIAS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD=$P12_GENESIS_FILE_PASSWORD --no-cache
     else
       echo "Building Global L0 image... (USING CACHE)"
-      docker-compose build --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_KEY_ALIAS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD=$P12_GENESIS_FILE_PASSWORD --no-cache
+      $dockercompose build --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_KEY_ALIAS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD=$P12_GENESIS_FILE_PASSWORD --no-cache
     fi
     echo "Global L0 image built"
 
@@ -313,13 +338,13 @@ build() {
   fi
 
   if [[ ! -z "$argc_include_dag_l1" || "$argc_only" == "dag-l1" ]]; then
-    cd dag-l1 || exit
+    cd dag-l1
     if [ ! -z "$argc_no_cache" ]; then
       echo "Building DAG L1 image... (NO CACHE)"
-      docker-compose build --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD --no-cache
+      $dockercompose build --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD --no-cache
     else
       echo "Building DAG L1 image... (USING CACHE)"
-      docker-compose build --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD
+      $dockercompose build --build-arg TESSELLATION_VERSION=$TESSELLATION_VERSION --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD
     fi
     echo "DAG L1 image built"
 
@@ -338,13 +363,13 @@ build() {
   if [[ -z "$argc_only" || "$argc_only" == "currency-l0" ]]; then
     export SHOULD_RESET_GENESIS_FILE=true
 
-    cd currency-l0 || exit
+    cd currency-l0
     if [ ! -z "$argc_no_cache" ]; then
       echo "Building Currency L0 image... (NO CACHE)"
-      docker-compose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_KEY_ALIAS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD=$P12_GENESIS_FILE_PASSWORD --no-cache
+      $dockercompose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_KEY_ALIAS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD=$P12_GENESIS_FILE_PASSWORD --no-cache
     else
       echo "Building Currency L0 image... (USING CACHE)"
-      docker-compose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_KEY_ALIAS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD=$P12_GENESIS_FILE_PASSWORD --no-cache
+      $dockercompose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_KEY_ALIAS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD=$P12_GENESIS_FILE_PASSWORD --no-cache
     fi
     echo "Currency L0 image built"
 
@@ -358,13 +383,13 @@ build() {
   fi
 
   if [[ -z "$argc_only" || "$argc_only" == "currency-l1" ]]; then
-    cd currency-l1 || exit
+    cd currency-l1
     if [ ! -z "$argc_no_cache" ]; then
       echo "Building Currency L1 image... (NO CACHE)"
-      docker-compose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD --no-cache
+      $dockercompose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD --no-cache
     else
       echo "Building Currency L1 image... (USING CACHE)"
-      docker-compose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD
+      $dockercompose build --build-arg TEMPLATE_NAME=$PROJECT_NAME --build-arg GIT_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN --build-arg P12_FILE_NAME_GENESIS=$P12_GENESIS_FILE_NAME --build-arg P12_FILE_NAME_NODE_2=$P12_NODE_2_FILE_NAME --build-arg P12_FILE_NAME_NODE_3=$P12_NODE_3_FILE_NAME --build-arg P12_FILE_KEY_ALIAS_GENESIS=$P12_GENESIS_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_2=$P12_NODE_2_FILE_KEY_ALIAS --build-arg P12_FILE_KEY_ALIAS_NODE_3=$P12_NODE_3_FILE_KEY_ALIAS --build-arg P12_FILE_PASSWORD_GENESIS=$P12_GENESIS_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_2=$P12_NODE_2_FILE_PASSWORD --build-arg P12_FILE_PASSWORD_NODE_3=$P12_NODE_3_FILE_PASSWORD
     fi
     echo "Currency L1 image built"
 
@@ -381,13 +406,13 @@ build() {
   fi
 
   if [[ -z "$argc_only" || "$argc_only" == "monitoring" ]]; then
-    cd monitoring || exit
+    cd monitoring
     if [ ! -z "$argc_no_cache" ]; then
       echo "Building monitoring image... (NO CACHE)"
-      docker-compose build --no-cache
+      $dockercompose build --no-cache
     else
       echo "Building monitoring image... (USING CACHE)"
-      docker-compose build
+      $dockercompose build
     fi
     echo "monitoring image built"
 
@@ -418,13 +443,15 @@ build() {
   fi
 
   echo "Cleaning up dangling docker images"
-  docker rmi $(docker images -f "dangling=true" -q) &>/dev/null
+  docker image prune -f
+  exit
 }
 
 # @cmd Start containers
 # @flag   --include_dag_l1           Includes the dag l1 layer to build/run
 # @option --only                     Build specific layer. Options: global-l0, dag-l1, currency-l0, currency-l1, monitoring
 start_genesis() {
+  set_docker_compose
   OUTPUT_YELLOW=$(tput setaf 3)
   OUTPUT_WHITE=$(tput setaf 7)
 
@@ -432,26 +459,26 @@ start_genesis() {
   if [[ -z "$argc_only" || "$argc_only" == "global-l0" ]]; then
     if ! docker inspect --type=image global-l0 &>/dev/null; then
       echo "You need to build the Global L0 first"
-      exit
+      exit 1
     fi
   fi
   if [[ -z "$argc_only" || "$argc_only" == "currency-l0" ]]; then
     if ! docker inspect --type=image currency-l0 &>/dev/null; then
       echo "You need to build the Currency L0 first"
-      exit
+      exit 1
     fi
   fi
   if [[ -z "$argc_only" || "$argc_only" == "currency-l1" ]]; then
     if ! docker inspect --type=image currency-l1-initial-validator &>/dev/null; then
       echo "You need to build the Currency L1 first"
-      exit
+      exit 1
     fi
   fi
 
   if [[ ! -z "$argc_include_dag_l1" || "$argc_only" == "dag-l1" ]]; then
     if ! docker inspect --type=image dag-l1-initial-validator &>/dev/null; then
       echo "You need to build the DAG L1 first"
-      exit
+      exit 1
     fi
   fi
 
@@ -475,7 +502,7 @@ start_genesis() {
   if [ ! -z "$argc_only" ]; then
     if [[ ! $VALID_ONLY_OPTIONS =~ (^|[[:space:]])$argc_only($|[[:space:]]) ]]; then
       echo "You should provide a valid only option"
-      exit
+      exit 1
     fi
   fi
 
@@ -543,14 +570,14 @@ start_genesis() {
 # @cmd Stop containers
 # @option --only                     Build specific layer. Options: global-l0, dag-l1, currency-l0, currency-l1, monitoring
 stop() {
+  set_docker_compose
   check_if_docker_is_running
   BASEDIR=$(dirname "$0")
-  cd $BASEDIR || exit
+  cd $BASEDIR
   if [ -d "scripts" ]; then
     cd scripts/
   fi
   cd ..
-  chmod -R +w source
 
   echo "Starting stopping containers ..."
 
@@ -581,16 +608,16 @@ stop() {
 # @flag   --delete_project            Delete custom project
 # @option --only                     Build specific layer. Options: global-l0, dag-l1, currency-l0, currency-l1, monitoring
 destroy() {
+  set_docker_compose
   check_if_docker_is_running
   BASEDIR=$(dirname "$0")
-  cd $BASEDIR || exit
+  cd $BASEDIR
   if [ -d "scripts" ]; then
     cd scripts/
   fi
 
   source ../.env
   cd ..
-  chmod -R +w source
 
   echo "Starting destroying containers ..."
 
@@ -625,12 +652,13 @@ destroy() {
   destroy_container ubuntu-with-java-and-sbt
 
   docker network rm custom-network
-  docker rmi $(docker images -f "dangling=true" -q) &>/dev/null
+  docker image prune -f
 }
 
 # @cmd Check the status of the containers
 # @flag  --show_all    Show all containers, including the stopped
 status() {
+  set_docker_compose
   check_if_docker_is_running
   if [[ ! -z "$argc_show_all" ]]; then
     docker ps -a --format "table {{.Names}}\t{{.Ports}}\t{{.Status}}"
